image_captioning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("main_page.urls"))
]

main_page/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path("", views.index, name='index'),
    path("predict", views.predict, name='predict')
]

main_page/models.py
from django.db import models

# Create your models here.

main_page/views.py
from django.shortcuts import render
from django.http import HttpResponse
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import argparse
from pickle import dump, load
from keras.models import Model, load_model
from keras.applications.xception import Xception, preprocess_input
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.image import load_img, img_to_array
import os
from pathlib import Path
from googletrans import Translator
from gtts import gTTS
from django.core.files.storage import FileSystemStorage
translator = Translator(service_urls=['translate.googleapis.com','translate.google.com','translate.google.co.kr'])
BASE_DIR = os.path.dirname(os.path.realpath(__file__))
model=load_model(os.path.join(BASE_DIR,"model_9_1.h5"))
tokenizer = load(open(os.path.join(BASE_DIR,"tokenizer_1.p"),"rb"))
text=""
max_length = 32
xception_model = Xception(include_top=False, pooling="avg")

def index(request):
    return render(request, "main_page/index.html")

def predict(request):
    global text
    try:
        if request.method == 'POST' and request.FILES['myfile']:
            myfile = request.FILES['myfile']
            fs = FileSystemStorage()
            os.remove(os.path.join(BASE_DIR,"static/main_page/img.jpg"))
            filename = fs.save(os.path.join(BASE_DIR,"static/main_page/img.jpg"), myfile)
            photo = extract_features(filename, xception_model)
            description = generate_desc(model, tokenizer, photo, max_length)
            words = description.split()
            red="red"
            filtered_sentence = [w for w in words if not w in red]
            textl=filtered_sentence[1:-1]
            text = ' '.join([str(elem) for elem in textl])
            print(text)
            result = translator.translate(text, src='en', dest='ne')
            text=result.text
            tts = gTTS(text=result.text,lang='ne',slow=False)
            tts.save(os.path.join(BASE_DIR,'static/main_page/sound.mp3'))
            return render(request, "main_page/predict.html",{"text":text})


    except Exception as e:
        return HttpResponse("<h1> Please upload image for auto caption</h1>") 

def extract_features(filename, model):
        try:
            image = load_img(filename, target_size=(299, 299))
            image = img_to_array(image)
            image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
            image = preprocess_input(image)
            feature = model.predict(image)
            return feature
        except:
            print("ERROR: Couldn't open image! Make sure the image path and extension is correct")

def word_for_id(integer, tokenizer):
    for word, index in tokenizer.word_index.items():
         if index == integer:
             return word
    return None


def generate_desc(model, tokenizer, photo, max_length):
    in_text = 'start'
    for i in range(max_length):
        sequence = tokenizer.texts_to_sequences([in_text])[0]
        sequence = pad_sequences([sequence], maxlen=max_length)
        pred = model.predict([photo,sequence], verbose=0)
        pred = np.argmax(pred)
        word = word_for_id(pred, tokenizer)
        if word is None:
            break
        in_text += ' ' + word
        if word == 'end':
            break
    return in_text

main_page/templates/main_page/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="target-densityDpi=device-dpi, width=device-width, height=device-height, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'main_page/bootstrap.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'main_page/index.css' %}">
    <style media="screen">
    .image-upload>input {
      display: none;
      }
    </style>
    <title>Image Caption</title>
  </head>
  <body>
    <h1 class="text">Image Captioning</h1>
    <form  method="post" action="{% url 'app:predict' %}" enctype="multipart/form-data">
   {% csrf_token %}
   <div class="text-center pt-4 image-upload">
     <label for="file-input">
    <img width="30%" src="https://icon-library.net/images/upload-photo-icon/upload-photo-icon-21.jpg"/>
  </label>
     <input id="file-input"  type="file" name="myfile"  accept="image/*" onchange="loadFile(event)">
   </div>
   <div  class="text-center p-1">
     <button class="box" type="submit">Predict</button>
   </div>
   <p class="text-center pt-2"><img id="output" width="90%" /></p>
   </form>
  {{text}}
  </body>
</html>

<script>
var loadFile = function(event) {
	var image = document.getElementById('output');
	image.src = URL.createObjectURL(event.target.files[0]);
};
</script>

main_page/templates/main_page/predict.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="target-densityDpi=device-dpi, width=device-width, height=device-height, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'main_page/bootstrap.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'main_page/index.css' %}">
    <title>Image Caption</title>
  </head>

  <body>
    <br><br>
    <form action="{% url 'app:index' %}" method="post">
    <h1 class="text-center p-4 text">{{text}}</h1>
    {% csrf_token %}
<hr>
<div class="text-center p-4">
  <button type="submit" name="button" class="box">GO BACK</button>
</div>

  </form>
</body>
</html>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var audio = new Audio("{% static 'main_page/sound.mp3' %}");
    audio.play();
});
</script>